language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.1
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - dotnet tool install --global coverlet.console
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
script:
  - ./build.sh
deploy:
  - provider: script
    script: docker build -t blackjacksoftware/rpthreadtrackerv3.backend .
    skip_cleanup: true
    on:
      tags: true
