version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - production
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./RPThreadTrackerV3.TumblrClient/RPThreadTrackerV3.TumblrClient.csproj --verbosity m
build_script:
  # output will be in ./src/bin/Release/netcoreapp2.0/publish
  - cmd: dotnet publish ./RPThreadTrackerV3.TumblrClient/RPThreadTrackerV3.TumblrClient.csproj -c Release
after_build:
  # For once the build has completed
artifacts:
 - path: '\RPThreadTrackerV3.TumblrClient\bin\Release\netcoreapp2.0\publish'
   name: TumblrClient
   type: WebDeployPackage
clone_depth: 1
on_finish :
  # any cleanup in here
deploy:
  - provider: Environment
    name: RPThreadTrackerV3-TumblrClient-Production