echo "Initializing database"
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Passw@rd' -i "/opt/scripts/000 - Initialize Database.sql"
echo "Adding AspNetUsers"
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Passw@rd' -i "/opt/scripts/010 - Add AspNetUsers.sql"
echo "Adding UserSetting"
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Passw@rd' -i "/opt/scripts/030 - Add UserSetting.sql"
echo "Adding Platforms"
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Passw@rd' -i "/opt/scripts/045 - Add Platforms.sql"
echo "Adding Characters"
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Passw@rd' -i "/opt/scripts/050 - Add Characters.sql"
echo "Adding Threads"
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Passw@rd' -i "/opt/scripts/070 - Add Threads.sql"
echo "Adding thread tags"
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Passw@rd' -i "/opt/scripts/090 - Add Thread Tags.sql"
echo "Adding logging table"
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Passw@rd' -i "/opt/scripts/110 - Add Logging Table.sql"
echo "Adding refresh token table"
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Passw@rd' -i "/opt/scripts/120 - Add Refresh Token Table.sql"
