sqlcmd /S "(localdb)\mssqllocaldb" -E -i"000 - Initialize Database.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"__Rollback.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"010 - Add AspNetUsers.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"020 - Migrate Into AspNetUsers.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"030 - Add UserSetting.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"040 - Migrate into UserSetting.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"045 - Add Platforms.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"050 - Add Characters.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"060 - Migrate into Characters.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"070 - Add Threads.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"080 - Migrate into Threads.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"090 - Add Thread Tags.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"100 - Migrate into Thread Tags.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"110 - Add Logging Table.sql"
sqlcmd /S "(localdb)\mssqllocaldb" /d "RPThreadTracker" -E -i"120 - Add Refresh Token Table.sql"
pause
